version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  pre_build:
    commands:
      # Optionally, run any pre-build tasks or scripts
      - echo running pre-bild

  build:
    commands:
      # Run your build tasks, tests, etc.
      - echo running build
      - npm i package
      - npm run build

artifacts:
  files:
    - app.js
    - package-lock.json
    - package.json
    - node_modules/*
